### PR TITLE
Add User Settings dialog

### PR DESCRIPTION
**Pull request by vsaarinen**
Add a user settings dialog to the dropdown with username, password and Git credentials sections:
screenshot 2017-05-02 17 01 35

TODO:
- [x] Merge #239 and rebase this onto master

### CODE REVIEW

**Comment by pekkapulli** [comment]
Functionality looks good 👍

**Comment by dennari** [comment]
The information hierarchy and layout works well. I'd simplify the password section to only include a 'reset password' button instead of a 'click here' link, which I believe is not regarded as especially good practice. After the email has been sent, the text could say 'Sent a password reset email to foo@bar.com'.

**Comment by dennari** [comment]
The 'Username' section talks about the 'username' and the 'Minard email address'. I'd stick to just a single term.

Also, maybe just use black with the usernames. It's a bit confusing as the some of the bold lime colored texts are links and some not.

**Comment by dennari** [comment]
Nice! 

I'd still consider only showing the 'A password reset email was sent to ville.vaananen@lucify.com.' after the button has been clicked. Now the same email address is repeated three times, once per section.

**Pull request merged**
