### PR TITLE
Use yarn, awesome-typescript-loader and webpack-dev-server 2

### PR DESCRIPTION
**Pull request by vsaarinen**
This PR does a few things:
- Starts using Yarn instead of NPM. It's faster and allows us to lock dependencies to specific versions easily. Minard builds are still built using NPM, but we can fix that in a future PR.
- Switch out ts-loader and babel-loader for [awesome-typescript-loader](https://github.com/s-panferov/awesome-typescript-loader). It should be a bit faster, especially when using babel (as we do).
- Speed up builds in dev mode by using a faster sourcemap option.
- Upgrade to webpack-dev-server version 2
- Update other packages
- Add missing tslint devDependencies
- Add some webpack optimizations and named modules for dev mode
- Clean up the webpack config files, especially by using `webpack-merge`

My initial goal for the PR was to reduce the size of our output thanks to Webpack 2's [tree-shaking](https://github.com/blacksonic/babel-webpack-tree-shaking), but I was unable to reduce the size in the end. I think this is due to our flow of TS => ES6 => Babel => ES5 instead of TS => ES5. Or then it might be because [tree-shaking might be broken in Webpack 2](https://github.com/webpack/webpack/issues/2867). Once TS adds support for generators with TS2.3, we can try again without Babel.

### CODE REVIEW

**Comment by vsaarinen** [comment]
The size of the output can be compared by running
```
NODE_ENV=production npm run build
```
before this PR and
```
NODE_ENV=production yarn run build
```
after.

**Comment by dennari** [comment]
When loading minard-ui in the browser I get
```
Uncaught TypeError: classNames is not a function
```

It seems that `classNames` should be imported with
```
import { classNames } from 'classnames';
```

**Comment by vsaarinen** [comment]
Note that `brew install yarn` will install a second copy of `node` if you've used NVM to install Node. It shouldn't affect anything (other than using up disk space), but if you really want to avoid it, you should be able to install yarn with `npm install -g yarn`. This is not the recommended way of installing yarn, however.

**Comment by dennari** [comment]
Ok good, works nicely! FYI: I had to empty the `.awcache` folder to see the improvements. This is something to keep in mind when debugging.

**Pull request merged**
