### PR TITLE
Simplify static asset hosting

### PR DESCRIPTION
**Pull request by vsaarinen**
We now lose hashes from the filenames of favicons, but the upside is that the system is simpler to understand – e.g. no need to understand where the Handlebars variables come from.

This is subjective, but I feel that it doesn't matter much if a cached favicon or logo file is seen by the user for a while after deploying a new version, so the downside is smaller than the upside.

### CODE REVIEW

**Comment by dennari** [comment]
I agree that the Handlebars shenanigans make this irritatingly complex. But losing the hashes has consequences as well, since all the hashed assets can be cached indefinitely.

**Comment by dennari** [comment]
Going forward, I'd advocate getting rid of Handlebars completely - like in lucify-website-next. Getting hashed asset paths in the template is then no different from getting then in the components.

**Comment by vsaarinen** [comment]
Yep, we should probably get rid of Handlebars at some point.

**Comment by juhoojala** [comment]
:+1:

**Pull request merged**
