### PR TITLE
Upgrade packages and separate vendor code

### PR DESCRIPTION
**Pull request by vsaarinen**
This PR updates packages and separates vendor code (i.e. packages from NPM) into a separate file. This allows us to cache all the vendor code (~80% of our generated code) across deployments if dependencies don't change.

This can be tested by making a production build (`NODE_ENV=production yarn run build`), storing the filenames (hashes) of the generated `.js` files, making a change to the source code, rebuilding, and making sure that the vendor file doesn't change.

### CODE REVIEW

**Comment by vsaarinen** [comment]
There's something weird going on with ES6 and UglifyJS. Investigating...

**Comment by vsaarinen** [comment]
This PR now also switches out UglifyJS in favor of Babili. The reason for this is that the generated code had ES6 features in it for some reason (from an NPM package, it seems), and UglifyJS only supports ES5. Babili also seems like a better option since it might allow us to do [tree-shaking](https://github.com/blacksonic/typescript-webpack-tree-shaking) at some point.

**Comment by vsaarinen** [comment]
Now also fixes Minard builds and adds test results for CircleCI.

**Comment by juhoojala** [comment]
:+1:

**Pull request merged**
